import React, { useEffect, useState } from "react";
import { Button } from "react-bootstrap";
import PaymentMethod from "../components/PaymentMethod";
import DonateForm from "../components/DonateForm";
import { useRef } from "react";

const Donate = () => {
  const [showDonateForm, setShowDonateForm] = useState(false);
  const [showPaymentMethod, setShowPaymentMethod] = useState(false);

  const donateFormRef = useRef(null);
  const handleDonateFormButton = () => {
    console.log("donate button clicked");
    setShowDonateForm(true);
    setShowPaymentMethod(true);
  };
  return (
    <div className="Donate">
      <h1 className="charity">YOU CAN DO IT CHARITY </h1>
      <h2>Support Us by Donating</h2>
      <p className="bg-info">Your Donation Can Change LIVES!</p>
      <p>
        Every donation, no matter the size, makes a real difference in the lives
        of those we serve. Your donation will help us continue our work towards
        creating a better future for all.
      </p>
      <div>
        <h2 className="quote bg-info">
          “We ourselves feel that what we are doing is just a drop in the ocean.
          But the ocean would be less because of that missing drop.”
          <br />
          ~Mother Teresa.
        </h2>

        <br />
        <div>
          <h2 className="quote1 bg-success">
            “Everybody can be great. Because anybody can serve. You don’t have
            to have a college degree to serve. You don’t have to make your
            subject and your verb agree to serve…. You don’t have to know the
            second theory of thermodynamics in physics to serve. You only need a
            heart full of grace. A soul generated by love.”
            <br />
            ~Martin Luther King, Jr
          </h2>

          <br />
          <h2 className="quote3 bg-warning">
            “The best way to find yourself is to lose yourself in the service of
            others.”
            <br />
            ~Mahatma Gandhi
          </h2>
          <br />
          <h2 className="quote2 bg-danger">
            “The smallest act of kindness is worth more than the grandest
            intention.”
            <br />
            ~Oscar Wilde
          </h2>
          <br />
          <div className="donate-form">
            {!showDonateForm && (
              <Button
                variant="success"
                onClick={(e) => {
                  handleDonateFormButton(e);
                }}
              >
                Donate Now
              </Button>
            )}
            <p>
              Data Privacy: We take utmost care of of your personal data and
              will never sell or share it to any third parties. Your
              confidential information such as credit card or bank details is
              not stored on our system and we do not call donors for their
              credit/debit card PIN or internet banking password.
            </p>
            {showDonateForm && (
              <DonateForm
                donateFormRef={donateFormRef}
                setShowDonateForm={setShowDonateForm}
                showDonateForm={showDonateForm}
                showPaymentMethod={showPaymentMethod}
              />
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Donate;
